// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wgexjzitvseahqhmazvb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndnZXhqeml0dnNlYWhxaG1henZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxNDUwODksImV4cCI6MjA4NDcyMTA4OX0.Qb8WWl4_sVTNwm1WQGMDn8NmNCy7WjN-dGOjaPF-Pak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});